Expense/Models/Addexpense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Expense.Models
{
    [Table("expenses")]
    public class Addexpense
    {
        [Key]
        public int Id { get; set; }

       [Required,RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$",ErrorMessage ="not allow numeric value")]
        public string Title { get; set; }

        [Required,RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage = "not allow numeric value")]
         public string Description { get; set; }

        public DateTime Date { get; set; } = DateTime.Now;

        public int Amount { get; set; }
        public int Cid { get; set; }

    }
}

Expense/Controllers/add_categoryController.cs
using Expense.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Expense.Controllers
{
    public class add_categoryController : Controller
    {
        // GET: add_category
        ExpenseContext exp = new ExpenseContext();
        public ActionResult Index()
        {
            IList<Addcategory> exlist = exp.adding_categories.ToList();

            return View(exlist);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Addcategory d)
        {
            exp.adding_categories.Add(d);
            int a = exp.SaveChanges();
            if (a > 0)
            {
                ViewBag.InsetMessage = "<script>alert('Data Inserted')</script>";
            }
            else
            {
                ViewBag.InsertMessage = "<script>alert('Data Not Inserted')</script>";
            }

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var raw = exp.adding_categories.Where(model => model.Cid == id).FirstOrDefault();

           return View(raw);
        }

        [HttpPost]
        public ActionResult Edit(Addcategory d)
        {
           exp.Entry(d).State = EntityState.Modified;
           int a = exp.SaveChanges();
           if (a > 0)
           {
              ViewBag.UpdateMessage = "<script>alret('Data Updataed')</script>";

          }
            else
            {
               ViewBag.UpdateMessage = "<script>alret('Data Not Updataed')</script>";

          }

            if (ModelState.IsValid)
            { //checking model state

                //update student to db

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
           var catraw = exp.adding_categories.Where(model => model.Cid == Id).FirstOrDefault();

            if (catraw != null)
            {
                exp.Entry(catraw).State = EntityState.Deleted;
                try
                {
                    int a = exp.SaveChanges();
                    if (a > 0)
                    {
                        TempData["Deleted"] = "<script>alert('Data Deleted')</script>";
                    }
                    else
                    {
                        TempData["Deleted"] = "<script>alert('Data Not Deleted')</script>";
                    }
                }
                catch
                {
                    TempData["Deleted"] = "<script>alert('first you delete your data in xpense list')</script>";
                }
            }        


            return RedirectToAction("Index");
        }


    }
}

Expense/Controllers/add_expenseController.cs
using Expense.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Expense.Controllers
{
    public class add_expenseController : Controller
    {
        // GET: add_expense
        ExpenseContext exp = new ExpenseContext();

        public ActionResult Index()
        {
            //var catteg = exp.adding_expense.ToList();
           // ViewBag.catteg = new SelectList(catteg, "Cid", "Categoryname");
            IList<Addexpense> elist = exp.adding_expense.ToList();

            return View(elist);
        }

        public ActionResult Create()
        {
            List<Addcategory> clist = exp.adding_categories.ToList();
            TempData["cname"] = new SelectList(clist, "Cid", "Categoryname");

            return View();

        }

        [HttpPost]
        public ActionResult Create(Addexpense s,Addcategory e)
            
        {

             var getamount = exp.adding_categories.Where(x => x.Cid == s.Cid).FirstOrDefault();
            if (getamount.Categorylimit > s.Amount)
            {

            IList<Addcategory> clist = exp.adding_categories.ToList();
                TempData["cname"] = new SelectList(clist, "Cid", "Categoryname");

                exp.adding_expense.Add(s);
                int a = exp.SaveChanges();
                if (a > 0)
                {
                    ViewBag.InsetMessage = "<Script>alert('Data Inserted')</script>";
                }
                else
                {

                    ViewBag.InsetMessage = "<Script>alert('Data Not Inserted')</script>";
                }
                
            }
            else
            {
                IList<Addcategory> clist = exp.adding_categories.ToList();
                TempData["cname"] = new SelectList(clist, "Cid", "Categoryname");
               ViewBag.msg = "<Script>alert(' Check calategory limit')</script>";

            }
            return View();

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            IList<Addcategory> clist = exp.adding_categories.ToList();
            TempData["cname"] = new SelectList(clist, "Cid", "Categoryname");

            var raw =exp.adding_expense.Where(model => model.Id == id).FirstOrDefault();

            return View(raw);
        }

        [HttpPost]
        public ActionResult Edit(Addexpense s)
        {
            IList<Addcategory> clist = exp.adding_categories.ToList();
            TempData["cname"] = new SelectList(clist, "Cid", "Categoryname");

            exp.Entry(s).State = EntityState.Modified;
            int a = exp.SaveChanges();
     

       

            if (a>0)
            {
                ViewBag.UpdateMessage = "<script>aleart('Data updatae')</scrit>";
            }
            else
            {
                ViewBag.UpdateMessage = "<script>aleart('Data Not updatae')</scrit>";

            }

            return RedirectToAction("Index");
        }
        [HttpPost]

        public ActionResult Delete(int id)
        {
            if(id>0)
            {
                var catraw = exp.adding_expense.Where(model => model.Id==id).FirstOrDefault();

                if (catraw!= null)
                {
                    exp.Entry(catraw).State = EntityState.Deleted;
                    int a = exp.SaveChanges();

                    if(a>0)
                    {
                        TempData["Deleted"]="<script>aleart('Data Deleted')</script>";
                    }
                    else
                    {
                        TempData["Deleted"] = "<script>aleart('Data Not Deleted')</script>";

                    }



                }
            }

            return RedirectToAction("Index");
        }
        public PartialViewResult Categories()
        {
            var cat = adding_categories();
            return PartialView("_categories", cat);
        }



        public IList<Addcategory> adding_categories()
        {
            return exp.adding_categories.ToList();
        }





    }
}

Expense/Views/add_expense/Create.cshtml
@model Expense.Models.Addexpense

@{
    ViewBag.Title = "Create";
}

@Html.Raw(ViewBag.msg)

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Addexpense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Cid, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Cid, TempData["cname"] as SelectList, "--select--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Expense/Views/add_expense/Edit.cshtml
@model Expense.Models.Addexpense

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Addexpense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Html.EditorFor(model => model.Cid, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Cid, TempData["cname"] as SelectList, "--select--", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.Cid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Expense/Views/add_expense/Index.cshtml
@model IEnumerable<Expense.Models.Addexpense>

@{
    ViewBag.Title = "Index";
}
@Html.Raw(ViewBag.msg)
<label style="background-color:hotpink">
    category name
</label>
<input type="text" name="text" />
<input type="submit" value="search" />
<style>
    .table {
        background-color: lightgoldenrodyellow;
    }

    #t {
        background-color: lightpink;
    }
</style>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" border="1">
    <tr id="t" style="color:darkblue" ;>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cid)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "add_expense", new { id = item.Id }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cid)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |



                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record with Category id=@item.Id');" style="color:red;" />

                </td>
            </tr>
        }
    }


</table>

@{
    Html.RenderAction("Categories");

}

Expense/Views/add_expense/_categories.cshtml
@model IEnumerable<Expense.Models.Addcategory>
<h2>Index</h2>

<p>

    @Html.ActionLink("Create New", "Create")

</p>

<style id="t" style="color:darkblue">
    .table {
        background-color: lightgoldenrodyellow;
    }

    #t {
        background-color: lightpink;
        text-align:center;
    }
</style>

<table class="table" border="1">
    <tr id="t" style="color:darkblue" ;>

        <th>
            @Html.DisplayNameFor(model => model.Cid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoryname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categorylimit)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "add_category", new { id = item.Cid }))
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Cid)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Categoryname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categorylimit)
                </td>

            </tr>
        }
    }

</table>